name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Access PUBLIC_API_KEY
        env:
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
        run: echo PUBLIC_API_KEY=\"PUBLIC_API_KEY\" > ./local.properties

      - name: Access PRIVATE_API_KEY
          env:
            PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
          run: echo PRIVATE_API_KEY=\"PPRIVATE_API_KEY\" > ./local.properties

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble